### ISSUE TITLE
TypeError: torch.index_select received an invalid combination of arguments - got (torch.FloatTensor, int, torch.cuda.LongTensor), but expected (torch.FloatTensor source, int dim, torch.LongTensor index)

### ISSUE THREAD

**Issue by eoc1991** [anhquan0412/basic_model_scratch#1]
Thanks a lot for your work! but when I run the code under "Model 1: Multiplying 2 embedding matrices",
`learner.fit(1e-2, 3, wds=1e-4, cycle_len=1,cycle_mult=2)`
there occurs a error  and I had no idea to it, Could you lend me a hand?

the environment is fastai based on paper'pass
![qq 20180917231030](https://user-images.githubusercontent.com/9986229/45631997-e0106400-bace-11e8-8885-caacd86cf41b.png)

**Comment by anhquan0412** [comment]
Hi,
The error is because some part of my notebook is not run on a GPU machine so I removed the 'cuda' function. Since you run it on GPU you should add .cuda() to the model to put the model on GPU, i.e in this case it will be 

```
em_model = EmbeddingMult(n_factors,cf.n_users,cf.n_items).cuda()
model = CollabFilterModel(em_model)
learner = CollabFilterLearner(cf.get_data(val_idxs,bs),model,opt_fn=optim.Adam)
learner.fit(1e-2, 3, wds=1e-4, cycle_len=1,cycle_mult=2)
```

Let me know if it helps!

**Comment by eoc1991** [comment]
It works,  thank you very much. :)

**Comment by anhquan0412** [comment]
No problem. Glad to help!
